// <auto-generated />
using System;
using JobMarket.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace JobMarket.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobMarket.Domain.Entities.CV", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AtsScore")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<int>("EnrichmentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CVs");
                });

            modelBuilder.Entity("JobMarket.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<int>("EnrichmentStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JobType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PostedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("numeric");

                    b.Property<int>("SeniorityLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("SourceJobId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Embedding")
                        .HasAnnotation("Npgsql:StorageParameter:lists", 100);

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "ivfflat");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("Source", "SourceJobId")
                        .IsUnique();

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("JobMarket.Domain.Entities.JobAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("JobAlerts");
                });

            modelBuilder.Entity("JobMarket.Domain.Entities.SkillTrend", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DemandCount")
                        .HasColumnType("integer");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Skill", "Date", "Source");

                    b.ToTable("SkillTrends");
                });

            modelBuilder.Entity("JobMarket.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("JobMarket.Domain.Entities.UserPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("PreferredJobType")
                        .HasColumnType("integer");

                    b.Property<string>("PreferredLocations")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("PreferredSeniority")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("JobMarket.Domain.Entities.WatchlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId", "JobId")
                        .IsUnique();

                    b.ToTable("WatchlistItems");
                });

            modelBuilder.Entity("JobMarket.Domain.Entities.CV", b =>
                {
                    b.HasOne("JobMarket.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("JobMarket.Domain.ValueObjects.AtsScoreBreakdown", "AtsBreakdown", b1 =>
                        {
                            b1.Property<Guid>("CVId");

                            b1.Property<int>("CompletenessScore");

                            b1.Property<int>("FormattingScore");

                            b1.Property<int>("KeywordScore");

                            b1.Property<int>("SkillRelevanceScore");

                            b1.PrimitiveCollection<string>("Suggestions")
                                .IsRequired();

                            b1.HasKey("CVId");

                            b1.ToTable("CVs");

                            b1
                                .ToJson("AtsBreakdown")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CVId");
                        });

                    b.OwnsOne("JobMarket.Domain.ValueObjects.CvParsedData", "ParsedData", b1 =>
                        {
                            b1.Property<Guid>("CVId");

                            b1.Property<string>("Email")
                                .IsRequired();

                            b1.Property<string>("FullName")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("Languages")
                                .IsRequired();

                            b1.Property<string>("Phone")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("Skills")
                                .IsRequired();

                            b1.Property<string>("Summary")
                                .IsRequired();

                            b1.Property<int>("TotalYearsExperience");

                            b1.HasKey("CVId");

                            b1.ToTable("CVs");

                            b1
                                .ToJson("ParsedData")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("CVId");

                            b1.OwnsMany("JobMarket.Domain.ValueObjects.Education", "Education", b2 =>
                                {
                                    b2.Property<Guid>("CvParsedDataCVId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Degree")
                                        .IsRequired();

                                    b2.Property<DateTime?>("EndDate");

                                    b2.Property<string>("Field")
                                        .IsRequired();

                                    b2.Property<string>("Institution")
                                        .IsRequired();

                                    b2.Property<DateTime?>("StartDate");

                                    b2.HasKey("CvParsedDataCVId", "__synthesizedOrdinal");

                                    b2.ToTable("CVs");

                                    b2.WithOwner()
                                        .HasForeignKey("CvParsedDataCVId");
                                });

                            b1.OwnsMany("JobMarket.Domain.ValueObjects.WorkExperience", "Experience", b2 =>
                                {
                                    b2.Property<Guid>("CvParsedDataCVId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Company")
                                        .IsRequired();

                                    b2.Property<string>("Description")
                                        .IsRequired();

                                    b2.Property<DateTime?>("EndDate");

                                    b2.Property<DateTime?>("StartDate");

                                    b2.Property<string>("Title")
                                        .IsRequired();

                                    b2.HasKey("CvParsedDataCVId", "__synthesizedOrdinal");

                                    b2.ToTable("CVs");

                                    b2.WithOwner()
                                        .HasForeignKey("CvParsedDataCVId");
                                });

                            b1.Navigation("Education");

                            b1.Navigation("Experience");
                        });

                    b.Navigation("AtsBreakdown");

                    b.Navigation("ParsedData");
                });

            modelBuilder.Entity("JobMarket.Domain.Entities.JobAlert", b =>
                {
                    b.HasOne("JobMarket.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobMarket.Domain.Entities.UserPreferences", b =>
                {
                    b.HasOne("JobMarket.Domain.Entities.User", null)
                        .WithOne("Preferences")
                        .HasForeignKey("JobMarket.Domain.Entities.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobMarket.Domain.Entities.WatchlistItem", b =>
                {
                    b.HasOne("JobMarket.Domain.Entities.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobMarket.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobMarket.Domain.Entities.User", b =>
                {
                    b.Navigation("Preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
